[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-g = "toothless-corner-serifless-hooked"
a = "double-storey-serifless"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "tailed"
g = "double-storey"
i = "hooky"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner"
u = "toothless-corner"
y = "straight-turn"
z = "straight-serifless"
lower-lambda = "straight-turn"
lower-xi = "rounded"
zero = "slashed"
one = "base"
six = "open-contour"
nine = "open-contour"
asterisk = "penta-low"
underscore = "high"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "lower-open"
dollar = "open"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
