[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-ligation = true

[buildPlans.iosevka-custom.variants.design]
ampersand = "upper-open"
asterisk = "penta-low"
b = "toothless-corner"
capital-g = "toothless-corner-serifless-hooked"
d = "toothless-corner-serifless"
dollar = "open"
g = "double-storey"
i = "hooky"
l = "tailed-serifed"
lig-ltgteq = "slanted"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
nine = "open-contour"
number-sign = "upright"
one = "base"
p = "earless-corner"
percent = "rings-continuous-slash-also-connected"
q = "earless-corner"
six = "open-contour"
u = "toothless-corner"
underscore = "high"
y = "straight-turn"
zero = "slashed"

# The following forces only regular font to be built
[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
